### ISSUE TITLE
I m having issue with the responce.

### ISSUE THREAD

**Issue by tayyab-skylinxtech** [srmklive/laravel-paypal#188] opened 2018-03-12 07:58 UTC
The Response content must be a string or object implementing __toString(), "object" given.

return redirect( $response['paypal_link'] );  this line is causing the isse. plz help

**Comment by srmklive** [comment] 2018-03-12 12:48
Duplicate of #100, #101, #102 & #149

**Closed by srmklive** 2018-03-12 12:48 UTC
