### ISSUE TITLE
Error has no message

### ISSUE THREAD

**Issue by janakad** [srmklive/laravel-paypal#228] opened 2018-07-26 10:00 UTC
I have added the following code:
```
$amount = $request->amount;
        $provider = PayPal::setProvider('express_checkout');

        $data = [];
        $data['items'] = [
            [
                'name' => 'Credits ' . $amount,
                'price' => 1,
                'qty' => $amount
            ]
        ];

        $data['invoice_id'] = 1;
        $data['invoice_description'] = "Order #{$data['invoice_id']} Invoice";
        $data['return_url'] = url('/payment/success');
        $data['cancel_url'] = url('/cart');

        $total = 0;
        foreach ($data['items'] as $item) {
            $total += $item['price'] * $item['qty'];
        }

        $data['total'] = $total;

//give a discount of 10% of the order amount
        $data['shipping_discount'] = 0;

        $response = $provider->setExpressCheckout($data);

        dd($response);
```

This is what printed from the response: 
```
array:3 [
  "type" => "error"
  "message" => ""
  "paypal_link" => null
]
```

How to debug this?

**Comment by srmklive** [comment] 2018-07-30 06:02
Duplicate of #100, #102

**Closed by srmklive** 2018-07-30 06:02 UTC
