### ISSUE TITLE
null paypal link

### ISSUE THREAD

**Issue by azztigz** [srmklive/laravel-paypal#236] opened 2018-08-29 14:34 UTC
![image](https://user-images.githubusercontent.com/12978297/44794699-99200480-abdb-11e8-989c-ec87a7f42c56.png)

**Comment by srmklive** [comment] 2018-09-03 11:37
Duplicate of #100, #101

**Comment by srmklive** [comment] 2018-09-03 11:37
Kindly check whether you are passing correct data to `SetExpressCheckout` API call.

**Closed by srmklive** 2018-09-03 11:37 UTC

**Comment by friana** [comment] 2019-03-14 08:46
This issue may be solve in this link. Thanks

https://github.com/srmklive/laravel-paypal/issues/229#issuecomment-472755054
