### ISSUE TITLE
Paypal responser return type error

### ISSUE THREAD

**Issue by batenko1** [srmklive/laravel-paypal#186] opened 2018-03-04 14:52 UTC
array:3 [▼
  "type" => "error"
  "message" => ""
  "paypal_link" => null
]

Paypal return. I can not understand what the problem is

**Comment by srmklive** [comment] 2018-03-05 12:15
Duplicate of #100, #101, #102 & #149

**Closed by srmklive** 2018-03-05 12:15 UTC

**Comment by himalaya-ahuja** [comment] 2018-04-02 11:56
It was working fine on local before , but not working on local anymore still working good on server , what could be the issue .? Credentials are fine for sandbox working on test server.
