### ISSUE TITLE
ExpressCheckout.php line 127: Undefined index: TOKEN

### ISSUE THREAD

**Issue by rahulnegi** [srmklive/laravel-paypal#104] opened 2017-05-19 06:35 UTC
Hi, 

I am using below code. but it showing me the Undefined index:token. 

<?php

namespace App\Http\Controllers;

// Import the class namespaces first, before using it directly
use Srmklive\PayPal\Services\ExpressCheckout;
//use Srmklive\PayPal\Services\AdaptivePayments;

use Illuminate\Http\Request;

use PayPal;

class PaypalPaymentController extends Controller
{
	
	
    public function payment()
	{

		 $provider = new ExpressCheckout;      // To use express checkout.
        //$provider = new AdaptivePayments;     // To use adaptive payments.
		
		
		// Through facade. No need to import namespaces
        $provider = PayPal::setProvider('express_checkout');      // To use express checkout(used by default).
        //$provider = PayPal::setProvider('adaptive_payments');     // To use adaptive payments.
		
		
		$data = [];
$data['items'] = [
    [
        'name' => 'Product 1',
        'price' => 9.99,
        'qty' => 1
    ],
    [
        'name' => 'Product 2',
        'price' => 4.99,
        'qty' => 2
    ]
];

$data['invoice_id'] = 1;
$data['invoice_description'] = "Order #{$data['invoice_id']} Invoice";
$data['return_url'] = url('/payment/success');
$data['cancel_url'] = url('/cart');

$total = 0;
foreach($data['items'] as $item) {
    $total += $item['price']*$item['qty'];
}

$data['total'] = $total;

		$options = [
    'BRANDNAME' => 'MyBrand',
    'LOGOIMG' => 'https://example.com/mylogo.png',
    'CHANNELTYPE' => 'Merchant'
];

$response = $provider->setExpressCheckout($data);

 // This will redirect user to PayPal
return redirect($response['paypal_link']);
dd($response);
		
	}
}

**Comment by srmklive** [comment] 2017-05-19 06:42
Duplicate of #100.

**Comment by srmklive** [comment] 2017-05-19 06:43
Please refer to the thread on #100 & #103

**Closed by srmklive** 2017-05-19 06:42 UTC

**Comment by rahulnegi** [comment] 2017-05-19 07:21
@srmklive I have checked the paypal send box credentials are correct.

Username, Password, secret,certificate attached, app_id (APP-80W284485P519543T).

Still same Undefined index: TOKEN error message. 

Please do need full.

**Comment by srmklive** [comment] 2017-05-19 07:24
@rahulnegi Kindly refer to the threads i mentioned in my previous comment.

**Comment by rahulnegi** [comment] 2017-05-19 08:03
Thanks I have used your demo application its awesome. But transactions are not going in Paypal sendbox funding. 

Error processing PayPal payment for Order (no).

Could you help me why this message showing?

**Comment by srmklive** [comment] 2017-05-19 09:13
You need to update the credentials in `config/paypal.php` accordingly to your requirements. Then it should work.

**Comment by rahulnegi** [comment] 2017-05-19 09:25
I have updated below for testing 
username'    => env('PAYPAL_SANDBOX_API_USERNAME', 'rahul.negi-facilitator_api1.iskpro.com'),
        'password'    => env('PAYPAL_SANDBOX_API_PASSWORD', '88EUWZLZ5V7WRK6Q'),
        'secret'      => env('PAYPAL_SANDBOX_API_SECRET', 'EP7UjUeABLNUqFThKCu3dcdvROIjPcQItjiwXdMnzSP3MupRXCujlWDe_btOS72ZdGfU7KXQs8zlfqjA'),
        'certificate' => env('PAYPAL_SANDBOX_API_CERTIFICATE', storage_path('cert_key_pem.txt')),
        'app_id'      => 'APP-80W284485P519543T', 

These all are sendbox credentials. Still not working

**Comment by srmklive** [comment] 2017-05-19 09:26
dude update all other parameters as well :laughing:

**Comment by rahulnegi** [comment] 2017-05-19 09:29
Do you mean to fill the below parameters as well ?

'live' => [
        'username'    => env('PAYPAL_LIVE_API_USERNAME', ''),
        'password'    => env('PAYPAL_LIVE_API_PASSWORD', ''),
        'secret'      => env('PAYPAL_LIVE_API_SECRET', ''),
        'certificate' => env('PAYPAL_LIVE_API_CERTIFICATE', ''),
        'app_id'      => '',         // Used for Adaptive Payments API
    ],

    'payment_action' => 'Sale', // Can Only Be 'Sale', 'Authorization', 'Order'
    'currency'       => 'USD',
    'notify_url'     => '', // Change this accordingly for your application.
    'locale'         => 'en_US', // force gateway language  i.e. it_IT, es_ES, en_US ... (for express checkout only)
    'invoice_prefix' => env('PAYPAL_INVOICE_PREFIX', 'PAYPALDEMOAPP')

**Comment by srmklive** [comment] 2017-05-19 09:37
yeah :smile:

**Comment by rahulnegi** [comment] 2017-05-19 09:43
I am confused now. If i am using only sandbox. Can't we leave blank on live?  I have already filled all parameter of sandbox except notify_url. 

Please explain me little bit more.

**Comment by srmklive** [comment] 2017-05-19 09:50
This should be crystal clear to you. SANDBOX credentials will work for Sandbox. Live will work for paypal live. `notify_url` will change depends on which mode you will use paypal.

How is that any confusing? You are not a baby. Start troubleshooting stuff if there is any confusion on your end.

**Comment by rahulnegi** [comment] 2017-05-19 09:56
@srmklive Chill Man.

**Comment by srmklive** [comment] 2017-05-19 10:02
You too :wink:. Try to figure things out on your own. That's the best i can tell you
