### ISSUE TITLE
"paypal_link" => null

### ISSUE THREAD

**Issue by dbos1504** [srmklive/laravel-paypal#198] opened 2018-04-14 23:07 UTC
I tried everything ( i mean everything, google, read everything from github, live and local), is it posible because i am from Serbia that paypal sanbox won t work...

**Comment by srmklive** [comment] 2018-04-15 12:02
Duplicate of #100, #101, #102 & #149

**Comment by srmklive** [comment] 2018-04-15 12:02
You need to provide correct api credentials for express checkout.

**Closed by srmklive** 2018-04-15 12:02 UTC

**Comment by friana** [comment] 2019-03-14 08:46
This issue may be solve in this link. Thanks

https://github.com/srmklive/laravel-paypal/issues/229#issuecomment-472755054
