### ISSUE TITLE
How to send custom parameter in AdaptivePayments to return in  IPN

### ISSUE THREAD

**Issue by jaymehtavaluecoders** [srmklive/laravel-paypal#191] opened 2018-03-19 09:47 UTC
HI , How to send custom parameter on AdaptivePayments , i have tried doing this 
But it does not work

$data = [
            'receivers'  => [
               
            ],
            'payer' => 'EACHRECEIVER',
            'return_url' => '', 
            'cancel_url' =>"" ,
            'custom' => ""  //This does not work
        ];

$data['items'] = [
            [
                'name'  => 'Payment for '.$details['campaign_name'],
                'price' => $details['amount'],
                'qty'   => 1,
            ],
        ];

**Comment by srmklive** [comment] 2018-03-19 12:16
Duplicate of #183.

**Closed by srmklive** 2018-03-19 12:16 UTC
